apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: wordpress
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
  - port: {{ .Values.wordpress.service.port }}
    targetPort: 80
    {{- if eq .Values.wordpress.service.type "NodePort" }}
    nodePort: {{ .Values.wordpress.service.nodePort }}
    {{- end }}
  selector:
    app: wordpress
