apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | b64enc | quote }}
